### ISSUE TITLE
`@Transactional`の付与位置について

### ISSUE THREAD

**Issue by ry-itto** [yt8492/SeihekiAnalyzerBot#4]
軽く気になったので。。。

### 気になる点
`@Transactional`をクラスのスコープにつけていると思いますが、
実際に処理としてDBに改変を加えるようなもの以外にはつける必要がないかなと思いました！

`@Transactional`をクラススコープにつけると暗黙的に全メソッドに付与されるようなので・・・

### 参考
[Spring @Transactionalのあれこれを検証してみた](https://qiita.com/kamikenta/items/5e20d00f3610601b2f67#transactinal%E3%82%92%E3%82%AF%E3%83%A9%E3%82%B9%E3%81%AB%E3%81%A4%E3%81%91%E3%82%8B%E3%81%A8%E3%82%AF%E3%83%A9%E3%82%B9%E5%86%85%E3%81%AE%E5%85%A8%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%81%AB%E3%81%A4%E3%81%8F)

**Comment by yt8492** [comment]
なるほど…ありがとうございます
そもそも `@Transactional` を間違ったところつけていたのに気づいた(おい)ので直します…
